	<link href='http://fonts.googleapis.com/css?family=Roboto+Slab:700,300' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:700' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.14.1/build/cssreset/cssreset-min.css">
	<link type="text/css" rel="stylesheet" href="stylesheethomepage.css"/>
	<link type="text/css" rel="stylesheet" href="stylesheetportfolio.css"/>
	<link type="text/css" rel="stylesheet" href="stylesheetprojectdetails.css"/>
	<link type="text/css" rel="stylesheet" href="stylesheetservices.css"/>
	<link type"text/css"  rel="stylesheet" href="stylesheetblog.css"/>
	<link type="text/css" rel="stylesheet" href="clearfix.css"/>
	<title><?php echo $title ?></title>
